### ISSUE TITLE
Image under "take a tour" overlaps the menu bar

### ISSUE THREAD

**Issue by kento726** [suncoast-devs/web#169]
The image under take a tour overlaps the menu bar. 
Add this in the css? 

tour-carousel {
z-index: -1;
}

<img width="873" alt="Screen Shot 2019-04-01 at 3 16 02 PM" src="https://user-images.githubusercontent.com/45078344/55353436-4d934900-5491-11e9-9e96-77c8be8b0396.png">

**Comment by ambethia** [comment]
Good catch!
