### ISSUE TITLE
Updating part-time dates

### ISSUE THREAD

**Issue by kento726** [suncoast-devs/web#275]
New web-dev test drive dates: Saturday, January 4, 2020 - Saturday, February 8, 2020

**Comment by LinnJS** [comment]
I will take this one if no one has started on it.

**Comment by lizthrilla** [comment]
I could be wrong @LinnJS but i think that is handled through the CMS

**Comment by lizthrilla** [comment]
Nevermind, that part isn't in the CMS, which explains why it doesn't get updated correctly sometimes.

**Comment by LinnJS** [comment]
@lizthrilla I can certainly add support to change this via CMS in the future.
