### ISSUE TITLE
Add Embarc Collective to https://suncoast.io/community/supporters as a Collaborator 

### ISSUE THREAD

**Issue by ToniWarren** [suncoast-devs/web#70]
![embarc_logo](https://user-images.githubusercontent.com/9707239/49038966-6f4f8d00-f18c-11e8-9889-b162dd10fb4f.png)

**Comment by ToniWarren** [comment]
@ambethia Can the external links open in a new tab?

**Comment by ambethia** [comment]
They can, but as I've mentioned before, I've _very_ strongly opposed to doing this, as I believe forcing a new tab creates a negative user experience. I'm open to discussion on it, but here are some resources that talk about the issue:

https://css-tricks.com/use-target_blank/
https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/
https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba
