### ISSUE TITLE
Application forms for scholarships

### ISSUE THREAD

**Issue by ambethia** [suncoast-devs/web#75]
Hanneke & Full-stack

**Comment by ToniWarren** [comment]
@ambethia I also wanted to check on the date of when you are changing the Diversity nav to say Diversity & Scholarships?

**Comment by ambethia** [comment]
Seeing as these are one-off scholarships for now, I'd like to bump this feature to `next` unless there are any objections.

**Comment by ktrammell95** [comment]
@ambethia We have google forms for the actual scholarship applicants at this time, just an FYI

**Comment by ambethia** [comment]
@ktrammell95 I know, this issue was for building custom forms into the website for them, like the program app and diversity scholarship. I feel the google forms are perfectly appropriate right now unless these become permanently funded scholarships and not one-time awards.
