### ISSUE TITLE
Link directly to each success story

### ISSUE THREAD

**Issue by ToniWarren** [suncoast-devs/web#82]
From https://suncoast.io/academy/success, so we can link directly to each alumni success story.

The pics also take a a few seconds to load and some are fuzzy. Can those be better optimized for load time?

**Comment by ambethia** [comment]
This change will be in the next iteration that I'm working on; it would require too much refactoring for it be a simple change right now.

The images are as optimized (systematically, using best practices like `srcset` for device-specific resolutions) as they can be already. In some cases, the original image provided is already lower resolution that appropriate and should be replaced with higher resolutions. I don't have the original images, perhaps @ktrammell95 can provide them.

**Comment by lizthrilla** [comment]
Just to add, with images on websites, the more images you have to load the longer the load time and eventually you have to choose between fast loading or super fuzzy images. Lazy loading (which is being implemented) and `srcset` are the way to go.

**Comment by ambethia** [comment]
Thanks @lizthrilla 

We're already lazy loading them, there's a base64 encoded preview that's embedded in the markup, then the resolution-specific file is loaded via `srcset`. It's about as optimized as we can make them.

**Comment by ktrammell95** [comment]
Why don't we do blog posts for each person?  That allows us to do a link and we can get more info on each person that will give people something better to read than just a short blip.  Plus adds more content to our website that we can then link out to the companies they work at and their LinkedIn profiles.

**Comment by ktrammell95** [comment]
@ambethia unless I took the pic I will not have original pics, most of these have been coming from the success story folks.

**Comment by ambethia** [comment]
Completed in relaunch
