### ISSUE TITLE
Update TampaBay WordPress meetup info on https://suncoast.io/community/

### ISSUE THREAD

**Issue by ktrammell95** [suncoast-devs/web#87]
New Title: WordPress St. Petersburg
New link: https://www.meetup.com/WordPress-St-Petersburg/
New Logo attached:
![wordpress](https://user-images.githubusercontent.com/10440779/49884874-e54a2a00-fe03-11e8-9c98-93342595454a.jpeg)

**Comment by jimtrue** [comment]
Thanks @ktrammell95 :)

**Comment by jimtrue** [comment]
![meetup-wpstepete](https://user-images.githubusercontent.com/3052875/49885455-4292ab00-fe05-11e8-91fd-d38f8bb503f0.jpg)

Let's use this one instead ;)

**Comment by jimtrue** [comment]
I also have it as a PNG if that helps.
![meetup-profile-stp](https://user-images.githubusercontent.com/3052875/49885573-a321e800-fe05-11e8-9e12-4d9d28be4d81.png)

**Comment by ambethia** [comment]
@ktrammell95 This can be done in Contentful now

**Comment by jimtrue** [comment]
@ambethia Do we need to join Contentful?

**Comment by jimtrue** [comment]
I gotcha, no problem, thanks @ambethia :)
