### ISSUE TITLE
Typos on catalog

### ISSUE THREAD

**Issue by kento726** [suncoast-devs/web#90]
Typos in our catalog shown in the screenshots below:

![2](https://user-images.githubusercontent.com/45078344/50020042-bf0ec080-ffa2-11e8-8702-567a488e350e.jpg)
![1](https://user-images.githubusercontent.com/45078344/50020043-bf0ec080-ffa2-11e8-92df-0c743acee2b6.jpg)

**Comment by ambethia** [comment]
Thanks Kento!
