### ISSUE TITLE
Staff titles say @ Suncoast Developers Guild on the Team page when you click for more

### ISSUE THREAD

**Issue by ktrammell95** [suncoast-devs/web#94]
Staff titles say @ Suncoast Developers Guild on the Team page when you click for more

![screen shot 2019-01-03 at 3 35 02 pm](https://user-images.githubusercontent.com/10440779/50660289-42517f80-0f6d-11e9-8055-6bc545b20769.png)

**Comment by ambethia** [comment]
Oh, that's odd. I swear it wasn't that way before.

**Comment by ambethia** [comment]
Oh oh, on the modal itself. I think that's fine.
