### ISSUE TITLE
Add EDC to https://suncoast.io/community/supporters/

### ISSUE THREAD

**Issue by ToniWarren** [suncoast-devs/web#95]
as Collaboration and link to
![official use logo](https://user-images.githubusercontent.com/9707239/50904208-bb2d5d00-13ed-11e9-8a88-86f2d48cac22.jpg)
 https://stpeteedc.com

**Comment by ambethia** [comment]
@ToniWarren These are managed from Contentful now, but I can take care of it. Did you get the invitation to Contentful?
