### ISSUE TITLE
Update Demo Day sites...

### ISSUE THREAD

**Issue by ToniWarren** [suncoast-devs/web#96]
with who is not available for hire and combine them to send out to hiring partners. Please let me know if you'd like a list of who specifically needs to be updated.  

Also add favicon to Cohort X and link backs to suncoast.io

http://cohort-x.surge.sh/ and https://demoday.suncoast.io/

**Comment by ToniWarren** [comment]
Is there a new link for this @ambethia?

**Comment by ambethia** [comment]
Oh, yes. I got so busy this week I hadn't put on the finishing touches yet (for example there's no way to browse from cohort-to-cohort yet). 

But for this week's purposes and directly sharing the URLs, it's live. Cohort XII just has to be added in Contentful and published. I will be working on this tomorrow.

Past cohorts can be viewed at https://suncoast.io/demo-day/cohor-x, etc.

I will also update the hireable flags tomorrow.
